### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by horridon** [hedii/php-crawler#7]
I'm still receiving a nasty error on last step when I'm trying to build:

```
[root@unit237 php-crawler2]# php artisan crawler:build
PHP Warning:  require(/var/www/html/php-crawler2/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/php-crawler2/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/php-crawler2/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/php-crawler2/bootstrap/autoload.php on line 17

```

**Comment by hedii** [comment]
You have not installed the package with composer create-project or you have a problem with composer.
Does composer work well on your system with other projects/packages?

try:

```
cd /var/www/html/php-crawler2
composer install
php artisan crawler:build
```

**Comment by horridon** [comment]
Outpot of composer install is: 

```
[root@unit237 php-crawler2]# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hedii/extractors 1.0.0 -> satisfiable by hedii/extractors[1.0.0].
    - hedii/extractors 1.0.0 requires php ~5.6|~7.0 -> your PHP version (5.5.33) does not satisfy that requirement.
  Problem 2
    - Installation request for laravel/framework v5.2.22 -> satisfiable by laravel/framework[v5.2.22].
    - laravel/framework v5.2.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for phpunit/phpunit 4.8.23 -> satisfiable by phpunit/phpunit[4.8.23].
    - phpunit/phpunit 4.8.23 requires ext-dom * -> the requested PHP extension dom is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php.ini
    - /etc/php.d/bz2.ini
    - /etc/php.d/calendar.ini
    - /etc/php.d/ctype.ini
    - /etc/php.d/curl.ini
    - /etc/php.d/exif.ini
    - /etc/php.d/fileinfo.ini
    - /etc/php.d/ftp.ini
    - /etc/php.d/gettext.ini
    - /etc/php.d/iconv.ini
    - /etc/php.d/json.ini
    - /etc/php.d/phar.ini
    - /etc/php.d/sockets.ini
    - /etc/php.d/tokenizer.ini
    - /etc/php.d/zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by hedii** [comment]
"your PHP version (5.5.33)"

you need a newer version of php, and you need to install php extensions: ext-dom and mbstring

**Comment by horridon** [comment]
Alright, let me update them and will come back with a new output.

**Comment by horridon** [comment]
And of course... more errors...

```
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\Console\json_decode() in phar:///usr/local/bin/composer/src/Composer/Console/Application.php:145
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(99): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/bin/composer(43): Composer\Console\Application->run()
#3 /usr/local/bin/composer(25): require('phar:///usr/loc...')
#4 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Console/Application.php on line 145

Fatal error: Uncaught Error: Call to undefined function Composer\Console\json_decode() in phar:///usr/local/bin/composer/src/Composer/Console/Application.php:145
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(99): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/bin/composer(43): Composer\Console\Application->run()
#3 /usr/local/bin/composer(25): require('phar:///usr/loc...')
#4 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Console/Application.php on line 145
```

**Comment by hedii** [comment]
The problems you are facing are not related with the repo code. Please answer the question I asked on the top of this issue.

**Comment by hedii** [comment]
no news, i close
